# Generated by Django 3.2.7 on 2021-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210927_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='district',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(default='---', max_length=30),
        ),
    ]
