# Generated by Django 3.2.7 on 2021-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210927_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Nationality',
        ),
        migrations.AddField(
            model_name='city',
            name='field',
            field=models.CharField(default='Read only field', max_length=30),
        ),
    ]
