# Generated by Django 3.2.7 on 2021-09-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_city_are_you_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
