# Generated by Django 3.2.7 on 2021-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_city_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
