# Generated by Django 3.2.7 on 2021-09-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
