# Generated by Django 3.2.7 on 2021-09-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210923_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Roll_no',
        ),
    ]
