# Generated by Django 3.2.7 on 2021-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210923_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Birth_Place',
        ),
    ]
