# Generated by Django 3.2.7 on 2021-09-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_city_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='District',
        ),
    ]
